//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.05 at 06:16:28 PM ICT 
//


package com.integrosys.sml.ws.dropdown.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.integrosys.sml.ws.loan.submission.ArrayOfTns4CommonCodeEntry;


/**
 * <p>Java class for Body complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Body">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="commonCodeEntries" type="{http://submission.loan.ws.sml.integrosys.com}ArrayOf_tns4_CommonCodeEntry"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Body", propOrder = {
    "commonCodeEntries"
})
public class Body {

    @XmlElement(required = true, nillable = true)
    protected ArrayOfTns4CommonCodeEntry commonCodeEntries;

    /**
     * Gets the value of the commonCodeEntries property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTns4CommonCodeEntry }
     *     
     */
    public ArrayOfTns4CommonCodeEntry getCommonCodeEntries() {
        return commonCodeEntries;
    }

    /**
     * Sets the value of the commonCodeEntries property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTns4CommonCodeEntry }
     *     
     */
    public void setCommonCodeEntries(ArrayOfTns4CommonCodeEntry value) {
        this.commonCodeEntries = value;
    }

}
