//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.05 at 06:16:28 PM ICT 
//


package com.integrosys.sml.ws.common;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.integrosys.sml.ws.common package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.integrosys.sml.ws.common
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CommonWSRequestHeader }
     * 
     */
    public CommonWSRequestHeader createCommonWSRequestHeader() {
        return new CommonWSRequestHeader();
    }

    /**
     * Create an instance of {@link CommonWSResponseHeader }
     * 
     */
    public CommonWSResponseHeader createCommonWSResponseHeader() {
        return new CommonWSResponseHeader();
    }

}
