//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.05 at 06:16:27 PM ICT 
//


package com.integrosys.sml.common.ob.feature;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Feature complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Feature">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="disbAcctName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="disbAcctNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="disbBankCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="requestAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="requestPercent" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="tenure" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Feature", propOrder = {
    "disbAcctName",
    "disbAcctNo",
    "disbBankCode",
    "id",
    "requestAmount",
    "requestPercent",
    "tenure"
})
public class Feature {

    @XmlElement(required = true, nillable = true)
    protected String disbAcctName;
    @XmlElement(required = true, nillable = true)
    protected String disbAcctNo;
    @XmlElement(required = true, nillable = true)
    protected String disbBankCode;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal id;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal requestAmount;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal requestPercent;
    @XmlElement(required = true, type = Long.class, nillable = true)
    protected Long tenure;

    /**
     * Gets the value of the disbAcctName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisbAcctName() {
        return disbAcctName;
    }

    /**
     * Sets the value of the disbAcctName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisbAcctName(String value) {
        this.disbAcctName = value;
    }

    /**
     * Gets the value of the disbAcctNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisbAcctNo() {
        return disbAcctNo;
    }

    /**
     * Sets the value of the disbAcctNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisbAcctNo(String value) {
        this.disbAcctNo = value;
    }

    /**
     * Gets the value of the disbBankCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisbBankCode() {
        return disbBankCode;
    }

    /**
     * Sets the value of the disbBankCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisbBankCode(String value) {
        this.disbBankCode = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setId(BigDecimal value) {
        this.id = value;
    }

    /**
     * Gets the value of the requestAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRequestAmount() {
        return requestAmount;
    }

    /**
     * Sets the value of the requestAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRequestAmount(BigDecimal value) {
        this.requestAmount = value;
    }

    /**
     * Gets the value of the requestPercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRequestPercent() {
        return requestPercent;
    }

    /**
     * Sets the value of the requestPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRequestPercent(BigDecimal value) {
        this.requestPercent = value;
    }

    /**
     * Gets the value of the tenure property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTenure() {
        return tenure;
    }

    /**
     * Sets the value of the tenure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTenure(Long value) {
        this.tenure = value;
    }

}
