//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.05 at 06:16:28 PM ICT 
//


package com.integrosys.sml.common.ob.dropdown;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommonCodeEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommonCodeEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="activeStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="categoryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="entryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="entryID" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="entryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="entryName2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="entrySource" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="extValue1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="extValue2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="refEntryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommonCodeEntry", propOrder = {
    "activeStatus",
    "categoryCode",
    "entryCode",
    "entryID",
    "entryName",
    "entryName2",
    "entrySource",
    "extValue1",
    "extValue2",
    "groupId",
    "refEntryCode"
})
public class CommonCodeEntry {

    @XmlElement(required = true, nillable = true)
    protected String activeStatus;
    @XmlElement(required = true, nillable = true)
    protected String categoryCode;
    @XmlElement(required = true, nillable = true)
    protected String entryCode;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal entryID;
    @XmlElement(required = true, nillable = true)
    protected String entryName;
    @XmlElement(required = true, nillable = true)
    protected String entryName2;
    @XmlElement(required = true, nillable = true)
    protected String entrySource;
    @XmlElement(required = true, nillable = true)
    protected String extValue1;
    @XmlElement(required = true, nillable = true)
    protected String extValue2;
    @XmlElement(required = true, nillable = true)
    protected String groupId;
    @XmlElement(required = true, nillable = true)
    protected String refEntryCode;

    /**
     * Gets the value of the activeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveStatus() {
        return activeStatus;
    }

    /**
     * Sets the value of the activeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveStatus(String value) {
        this.activeStatus = value;
    }

    /**
     * Gets the value of the categoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * Sets the value of the categoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryCode(String value) {
        this.categoryCode = value;
    }

    /**
     * Gets the value of the entryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryCode() {
        return entryCode;
    }

    /**
     * Sets the value of the entryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryCode(String value) {
        this.entryCode = value;
    }

    /**
     * Gets the value of the entryID property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEntryID() {
        return entryID;
    }

    /**
     * Sets the value of the entryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEntryID(BigDecimal value) {
        this.entryID = value;
    }

    /**
     * Gets the value of the entryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryName() {
        return entryName;
    }

    /**
     * Sets the value of the entryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryName(String value) {
        this.entryName = value;
    }

    /**
     * Gets the value of the entryName2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryName2() {
        return entryName2;
    }

    /**
     * Sets the value of the entryName2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryName2(String value) {
        this.entryName2 = value;
    }

    /**
     * Gets the value of the entrySource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntrySource() {
        return entrySource;
    }

    /**
     * Sets the value of the entrySource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntrySource(String value) {
        this.entrySource = value;
    }

    /**
     * Gets the value of the extValue1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtValue1() {
        return extValue1;
    }

    /**
     * Sets the value of the extValue1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtValue1(String value) {
        this.extValue1 = value;
    }

    /**
     * Gets the value of the extValue2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtValue2() {
        return extValue2;
    }

    /**
     * Sets the value of the extValue2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtValue2(String value) {
        this.extValue2 = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupId(String value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the refEntryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefEntryCode() {
        return refEntryCode;
    }

    /**
     * Sets the value of the refEntryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefEntryCode(String value) {
        this.refEntryCode = value;
    }

}
