//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.05 at 06:16:27 PM ICT 
//


package com.integrosys.sml.common.ob.pricing;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Pricing complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Pricing">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="calculatedRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ccId" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="facId" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="installment" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="interestRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="monthFrom" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="monthTo" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="percentSign" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pricingType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rateType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rateVaraince" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="tier" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="yearFrom" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="yearTo" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Pricing", propOrder = {
    "calculatedRate",
    "ccId",
    "facId",
    "id",
    "installment",
    "interestRate",
    "monthFrom",
    "monthTo",
    "percentSign",
    "pricingType",
    "rateType",
    "rateVaraince",
    "tier",
    "yearFrom",
    "yearTo"
})
public class Pricing {

    @XmlElement(required = true, nillable = true)
    protected BigDecimal calculatedRate;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal ccId;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal facId;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal id;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal installment;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal interestRate;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal monthFrom;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal monthTo;
    @XmlElement(required = true, nillable = true)
    protected String percentSign;
    @XmlElement(required = true, nillable = true)
    protected String pricingType;
    @XmlElement(required = true, nillable = true)
    protected String rateType;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal rateVaraince;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal tier;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal yearFrom;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal yearTo;

    /**
     * Gets the value of the calculatedRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCalculatedRate() {
        return calculatedRate;
    }

    /**
     * Sets the value of the calculatedRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCalculatedRate(BigDecimal value) {
        this.calculatedRate = value;
    }

    /**
     * Gets the value of the ccId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCcId() {
        return ccId;
    }

    /**
     * Sets the value of the ccId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCcId(BigDecimal value) {
        this.ccId = value;
    }

    /**
     * Gets the value of the facId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFacId() {
        return facId;
    }

    /**
     * Sets the value of the facId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFacId(BigDecimal value) {
        this.facId = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setId(BigDecimal value) {
        this.id = value;
    }

    /**
     * Gets the value of the installment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInstallment() {
        return installment;
    }

    /**
     * Sets the value of the installment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInstallment(BigDecimal value) {
        this.installment = value;
    }

    /**
     * Gets the value of the interestRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    /**
     * Sets the value of the interestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInterestRate(BigDecimal value) {
        this.interestRate = value;
    }

    /**
     * Gets the value of the monthFrom property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMonthFrom() {
        return monthFrom;
    }

    /**
     * Sets the value of the monthFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMonthFrom(BigDecimal value) {
        this.monthFrom = value;
    }

    /**
     * Gets the value of the monthTo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMonthTo() {
        return monthTo;
    }

    /**
     * Sets the value of the monthTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMonthTo(BigDecimal value) {
        this.monthTo = value;
    }

    /**
     * Gets the value of the percentSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercentSign() {
        return percentSign;
    }

    /**
     * Sets the value of the percentSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercentSign(String value) {
        this.percentSign = value;
    }

    /**
     * Gets the value of the pricingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricingType() {
        return pricingType;
    }

    /**
     * Sets the value of the pricingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricingType(String value) {
        this.pricingType = value;
    }

    /**
     * Gets the value of the rateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateType() {
        return rateType;
    }

    /**
     * Sets the value of the rateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateType(String value) {
        this.rateType = value;
    }

    /**
     * Gets the value of the rateVaraince property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRateVaraince() {
        return rateVaraince;
    }

    /**
     * Sets the value of the rateVaraince property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRateVaraince(BigDecimal value) {
        this.rateVaraince = value;
    }

    /**
     * Gets the value of the tier property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTier() {
        return tier;
    }

    /**
     * Sets the value of the tier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTier(BigDecimal value) {
        this.tier = value;
    }

    /**
     * Gets the value of the yearFrom property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getYearFrom() {
        return yearFrom;
    }

    /**
     * Sets the value of the yearFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setYearFrom(BigDecimal value) {
        this.yearFrom = value;
    }

    /**
     * Gets the value of the yearTo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getYearTo() {
        return yearTo;
    }

    /**
     * Sets the value of the yearTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setYearTo(BigDecimal value) {
        this.yearTo = value;
    }

}
