//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.05 at 06:16:27 PM ICT 
//


package com.integrosys.sml.common.ob.account;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Account complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Account">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accountNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accountStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accountType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bankName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bankNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cifId" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="cifName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cifRelationship" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cifRelationshipCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="exposureTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hostID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="identifiedBalType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="outstandingLimit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="outstandingLimitCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Account", propOrder = {
    "accountNo",
    "accountStatus",
    "accountType",
    "bankName",
    "bankNo",
    "cifId",
    "cifName",
    "cifRelationship",
    "cifRelationshipCode",
    "currency",
    "exposureTypeCode",
    "hostID",
    "id",
    "identifiedBalType",
    "outstandingLimit",
    "outstandingLimitCurrency",
    "productCode"
})
public class Account {

    @XmlElement(required = true, nillable = true)
    protected String accountNo;
    @XmlElement(required = true, nillable = true)
    protected String accountStatus;
    @XmlElement(required = true, nillable = true)
    protected String accountType;
    @XmlElement(required = true, nillable = true)
    protected String bankName;
    @XmlElement(required = true, nillable = true)
    protected String bankNo;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal cifId;
    @XmlElement(required = true, nillable = true)
    protected String cifName;
    @XmlElement(required = true, nillable = true)
    protected String cifRelationship;
    @XmlElement(required = true, nillable = true)
    protected String cifRelationshipCode;
    @XmlElement(required = true, nillable = true)
    protected String currency;
    @XmlElement(required = true, nillable = true)
    protected String exposureTypeCode;
    @XmlElement(required = true, nillable = true)
    protected String hostID;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal id;
    @XmlElement(required = true, nillable = true)
    protected String identifiedBalType;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal outstandingLimit;
    @XmlElement(required = true, nillable = true)
    protected String outstandingLimitCurrency;
    @XmlElement(required = true, nillable = true)
    protected String productCode;

    /**
     * Gets the value of the accountNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * Sets the value of the accountNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNo(String value) {
        this.accountNo = value;
    }

    /**
     * Gets the value of the accountStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountStatus() {
        return accountStatus;
    }

    /**
     * Sets the value of the accountStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountStatus(String value) {
        this.accountStatus = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountType(String value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the bankName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * Sets the value of the bankName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankName(String value) {
        this.bankName = value;
    }

    /**
     * Gets the value of the bankNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * Sets the value of the bankNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankNo(String value) {
        this.bankNo = value;
    }

    /**
     * Gets the value of the cifId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCifId() {
        return cifId;
    }

    /**
     * Sets the value of the cifId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCifId(BigDecimal value) {
        this.cifId = value;
    }

    /**
     * Gets the value of the cifName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCifName() {
        return cifName;
    }

    /**
     * Sets the value of the cifName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCifName(String value) {
        this.cifName = value;
    }

    /**
     * Gets the value of the cifRelationship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCifRelationship() {
        return cifRelationship;
    }

    /**
     * Sets the value of the cifRelationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCifRelationship(String value) {
        this.cifRelationship = value;
    }

    /**
     * Gets the value of the cifRelationshipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCifRelationshipCode() {
        return cifRelationshipCode;
    }

    /**
     * Sets the value of the cifRelationshipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCifRelationshipCode(String value) {
        this.cifRelationshipCode = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the exposureTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExposureTypeCode() {
        return exposureTypeCode;
    }

    /**
     * Sets the value of the exposureTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExposureTypeCode(String value) {
        this.exposureTypeCode = value;
    }

    /**
     * Gets the value of the hostID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostID() {
        return hostID;
    }

    /**
     * Sets the value of the hostID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostID(String value) {
        this.hostID = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setId(BigDecimal value) {
        this.id = value;
    }

    /**
     * Gets the value of the identifiedBalType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifiedBalType() {
        return identifiedBalType;
    }

    /**
     * Sets the value of the identifiedBalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifiedBalType(String value) {
        this.identifiedBalType = value;
    }

    /**
     * Gets the value of the outstandingLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOutstandingLimit() {
        return outstandingLimit;
    }

    /**
     * Sets the value of the outstandingLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOutstandingLimit(BigDecimal value) {
        this.outstandingLimit = value;
    }

    /**
     * Gets the value of the outstandingLimitCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutstandingLimitCurrency() {
        return outstandingLimitCurrency;
    }

    /**
     * Sets the value of the outstandingLimitCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutstandingLimitCurrency(String value) {
        this.outstandingLimitCurrency = value;
    }

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

}
