//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.05 at 06:16:27 PM ICT 
//


package com.integrosys.sml.common.ob.creditcard;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.integrosys.sml.common.ob.feature.Feature;
import com.integrosys.sml.ws.loan.submission.ArrayOfTns9Pricing;


/**
 * <p>Java class for InstantCreditCard complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InstantCreditCard">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="caId" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="campaignCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="campaignExpireDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="campaignStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="cardBrand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardDeliveryAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cifId" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="creditcardSavedFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="custSegment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="existCardName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="existCardNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="existCardStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="existCreditLimit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="existCreditLine" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="existProductType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="feature" type="{http://feature.ob.common.sml.integrosys.com}Feature"/>
 *         &lt;element name="featureType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="loanReqMax" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="loanReqMin" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="mailPreference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modelScore" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="newCreditLimit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="paymentMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pricings" type="{http://submission.loan.ws.sml.integrosys.com}ArrayOf_tns9_Pricing"/>
 *         &lt;element name="productCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="projectCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="requestCreditLimit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="saleChannelCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="saleChannelFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sourceOfData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InstantCreditCard", propOrder = {
    "caId",
    "campaignCode",
    "campaignExpireDate",
    "campaignStartDate",
    "cardBrand",
    "cardDeliveryAddress",
    "cardInd",
    "cifId",
    "creditcardSavedFlag",
    "custSegment",
    "existCardName",
    "existCardNumber",
    "existCardStatus",
    "existCreditLimit",
    "existCreditLine",
    "existProductType",
    "feature",
    "featureType",
    "id",
    "loanReqMax",
    "loanReqMin",
    "mailPreference",
    "modelName",
    "modelScore",
    "newCreditLimit",
    "paymentMethod",
    "pricings",
    "productCode",
    "productType",
    "projectCode",
    "requestCreditLimit",
    "saleChannelCode",
    "saleChannelFlag",
    "sourceOfData"
})
public class InstantCreditCard {

    @XmlElement(required = true, nillable = true)
    protected BigDecimal caId;
    @XmlElement(required = true, nillable = true)
    protected String campaignCode;
    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar campaignExpireDate;
    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar campaignStartDate;
    @XmlElement(required = true, nillable = true)
    protected String cardBrand;
    @XmlElement(required = true, nillable = true)
    protected String cardDeliveryAddress;
    @XmlElement(required = true, nillable = true)
    protected String cardInd;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal cifId;
    @XmlElement(required = true, nillable = true)
    protected String creditcardSavedFlag;
    @XmlElement(required = true, nillable = true)
    protected String custSegment;
    @XmlElement(required = true, nillable = true)
    protected String existCardName;
    @XmlElement(required = true, nillable = true)
    protected String existCardNumber;
    @XmlElement(required = true, nillable = true)
    protected String existCardStatus;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal existCreditLimit;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal existCreditLine;
    @XmlElement(required = true, nillable = true)
    protected String existProductType;
    @XmlElement(required = true, nillable = true)
    protected Feature feature;
    @XmlElement(required = true, nillable = true)
    protected String featureType;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal id;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal loanReqMax;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal loanReqMin;
    @XmlElement(required = true, nillable = true)
    protected String mailPreference;
    @XmlElement(required = true, nillable = true)
    protected String modelName;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal modelScore;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal newCreditLimit;
    @XmlElement(required = true, nillable = true)
    protected String paymentMethod;
    @XmlElement(required = true, nillable = true)
    protected ArrayOfTns9Pricing pricings;
    @XmlElement(required = true, nillable = true)
    protected String productCode;
    @XmlElement(required = true, nillable = true)
    protected String productType;
    @XmlElement(required = true, nillable = true)
    protected String projectCode;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal requestCreditLimit;
    @XmlElement(required = true, nillable = true)
    protected String saleChannelCode;
    @XmlElement(required = true, nillable = true)
    protected String saleChannelFlag;
    @XmlElement(required = true, nillable = true)
    protected String sourceOfData;

    /**
     * Gets the value of the caId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCaId() {
        return caId;
    }

    /**
     * Sets the value of the caId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCaId(BigDecimal value) {
        this.caId = value;
    }

    /**
     * Gets the value of the campaignCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCampaignCode() {
        return campaignCode;
    }

    /**
     * Sets the value of the campaignCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCampaignCode(String value) {
        this.campaignCode = value;
    }

    /**
     * Gets the value of the campaignExpireDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCampaignExpireDate() {
        return campaignExpireDate;
    }

    /**
     * Sets the value of the campaignExpireDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCampaignExpireDate(XMLGregorianCalendar value) {
        this.campaignExpireDate = value;
    }

    /**
     * Gets the value of the campaignStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCampaignStartDate() {
        return campaignStartDate;
    }

    /**
     * Sets the value of the campaignStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCampaignStartDate(XMLGregorianCalendar value) {
        this.campaignStartDate = value;
    }

    /**
     * Gets the value of the cardBrand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardBrand() {
        return cardBrand;
    }

    /**
     * Sets the value of the cardBrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardBrand(String value) {
        this.cardBrand = value;
    }

    /**
     * Gets the value of the cardDeliveryAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardDeliveryAddress() {
        return cardDeliveryAddress;
    }

    /**
     * Sets the value of the cardDeliveryAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardDeliveryAddress(String value) {
        this.cardDeliveryAddress = value;
    }

    /**
     * Gets the value of the cardInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardInd() {
        return cardInd;
    }

    /**
     * Sets the value of the cardInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardInd(String value) {
        this.cardInd = value;
    }

    /**
     * Gets the value of the cifId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCifId() {
        return cifId;
    }

    /**
     * Sets the value of the cifId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCifId(BigDecimal value) {
        this.cifId = value;
    }

    /**
     * Gets the value of the creditcardSavedFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditcardSavedFlag() {
        return creditcardSavedFlag;
    }

    /**
     * Sets the value of the creditcardSavedFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditcardSavedFlag(String value) {
        this.creditcardSavedFlag = value;
    }

    /**
     * Gets the value of the custSegment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustSegment() {
        return custSegment;
    }

    /**
     * Sets the value of the custSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustSegment(String value) {
        this.custSegment = value;
    }

    /**
     * Gets the value of the existCardName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExistCardName() {
        return existCardName;
    }

    /**
     * Sets the value of the existCardName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExistCardName(String value) {
        this.existCardName = value;
    }

    /**
     * Gets the value of the existCardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExistCardNumber() {
        return existCardNumber;
    }

    /**
     * Sets the value of the existCardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExistCardNumber(String value) {
        this.existCardNumber = value;
    }

    /**
     * Gets the value of the existCardStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExistCardStatus() {
        return existCardStatus;
    }

    /**
     * Sets the value of the existCardStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExistCardStatus(String value) {
        this.existCardStatus = value;
    }

    /**
     * Gets the value of the existCreditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExistCreditLimit() {
        return existCreditLimit;
    }

    /**
     * Sets the value of the existCreditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExistCreditLimit(BigDecimal value) {
        this.existCreditLimit = value;
    }

    /**
     * Gets the value of the existCreditLine property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExistCreditLine() {
        return existCreditLine;
    }

    /**
     * Sets the value of the existCreditLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExistCreditLine(BigDecimal value) {
        this.existCreditLine = value;
    }

    /**
     * Gets the value of the existProductType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExistProductType() {
        return existProductType;
    }

    /**
     * Sets the value of the existProductType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExistProductType(String value) {
        this.existProductType = value;
    }

    /**
     * Gets the value of the feature property.
     * 
     * @return
     *     possible object is
     *     {@link Feature }
     *     
     */
    public Feature getFeature() {
        return feature;
    }

    /**
     * Sets the value of the feature property.
     * 
     * @param value
     *     allowed object is
     *     {@link Feature }
     *     
     */
    public void setFeature(Feature value) {
        this.feature = value;
    }

    /**
     * Gets the value of the featureType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureType() {
        return featureType;
    }

    /**
     * Sets the value of the featureType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureType(String value) {
        this.featureType = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setId(BigDecimal value) {
        this.id = value;
    }

    /**
     * Gets the value of the loanReqMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLoanReqMax() {
        return loanReqMax;
    }

    /**
     * Sets the value of the loanReqMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLoanReqMax(BigDecimal value) {
        this.loanReqMax = value;
    }

    /**
     * Gets the value of the loanReqMin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLoanReqMin() {
        return loanReqMin;
    }

    /**
     * Sets the value of the loanReqMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLoanReqMin(BigDecimal value) {
        this.loanReqMin = value;
    }

    /**
     * Gets the value of the mailPreference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailPreference() {
        return mailPreference;
    }

    /**
     * Sets the value of the mailPreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailPreference(String value) {
        this.mailPreference = value;
    }

    /**
     * Gets the value of the modelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the modelScore property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getModelScore() {
        return modelScore;
    }

    /**
     * Sets the value of the modelScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setModelScore(BigDecimal value) {
        this.modelScore = value;
    }

    /**
     * Gets the value of the newCreditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNewCreditLimit() {
        return newCreditLimit;
    }

    /**
     * Sets the value of the newCreditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNewCreditLimit(BigDecimal value) {
        this.newCreditLimit = value;
    }

    /**
     * Gets the value of the paymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Sets the value of the paymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentMethod(String value) {
        this.paymentMethod = value;
    }

    /**
     * Gets the value of the pricings property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTns9Pricing }
     *     
     */
    public ArrayOfTns9Pricing getPricings() {
        return pricings;
    }

    /**
     * Sets the value of the pricings property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTns9Pricing }
     *     
     */
    public void setPricings(ArrayOfTns9Pricing value) {
        this.pricings = value;
    }

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductType(String value) {
        this.productType = value;
    }

    /**
     * Gets the value of the projectCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * Sets the value of the projectCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectCode(String value) {
        this.projectCode = value;
    }

    /**
     * Gets the value of the requestCreditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRequestCreditLimit() {
        return requestCreditLimit;
    }

    /**
     * Sets the value of the requestCreditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRequestCreditLimit(BigDecimal value) {
        this.requestCreditLimit = value;
    }

    /**
     * Gets the value of the saleChannelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaleChannelCode() {
        return saleChannelCode;
    }

    /**
     * Sets the value of the saleChannelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaleChannelCode(String value) {
        this.saleChannelCode = value;
    }

    /**
     * Gets the value of the saleChannelFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaleChannelFlag() {
        return saleChannelFlag;
    }

    /**
     * Sets the value of the saleChannelFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaleChannelFlag(String value) {
        this.saleChannelFlag = value;
    }

    /**
     * Gets the value of the sourceOfData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceOfData() {
        return sourceOfData;
    }

    /**
     * Sets the value of the sourceOfData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceOfData(String value) {
        this.sourceOfData = value;
    }

}
