//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.05 at 06:16:27 PM ICT 
//


package com.integrosys.sml.common.ob.individual;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.integrosys.sml.ws.loan.submission.ArrayOfTns5Account;
import com.integrosys.sml.ws.loan.submission.ArrayOfTns6Address;
import com.integrosys.sml.ws.loan.submission.ArrayOfTns7InstantCreditCard;


/**
 * <p>Java class for InstantIndividual complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InstantIndividual">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accounts" type="{http://submission.loan.ws.sml.integrosys.com}ArrayOf_tns5_Account"/>
 *         &lt;element name="addresses" type="{http://submission.loan.ws.sml.integrosys.com}ArrayOf_tns6_Address"/>
 *         &lt;element name="age" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ageMonth" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="benefitPlusSegment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="birthDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="birthPlace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bonusYearly" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="businessSubType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="businessType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="caId" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="cifId" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="cifRelCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="companyType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contractEmpEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="contractEmpStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="contractEmployedFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="countryOfRegAddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="creditCards" type="{http://submission.loan.ws.sml.integrosys.com}ArrayOf_tns7_InstantCreditCard"/>
 *         &lt;element name="currentEmployerCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="currentJobTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="custContactTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customerLevel" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="customerRiskRM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customerType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="discloseCustInfoFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="educationLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="emailStatementFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employmentBizNature" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employmentDept" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employmentFaxNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employmentFinalTotalIncome" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="employmentInfoSavedFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employmentMonth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employmentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employmentOccupation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employmentProvince" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employmentStaffId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employmentStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employmentTelephoneDirectNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employmentTelephoneExtNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employmentTelephoneNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employmentYear" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="excludeIncomeDebtFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="existingSavingTDAccount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="expiryDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="extTelephoneNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fixNetAsset" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hostCifNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idIssueCtry1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idNo1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idType1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idenPresentToBank" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inTotalExtraIncome" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="inTotalFixedIncome" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="inTotalIncome" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="inTotalOtherIncome" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="includeIncomeFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="incomeBankAccoutNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="incomeBankName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="incomeBasicSalary" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeDeclared" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeExtraOther" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeExtraRental" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeInfoSavedFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="incomeOtherCommAverage" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeOtherCommMonth1" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeOtherCommMonth2" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeOtherCommMonth3" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeOtherDiemAverage" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeOtherDiemMonth1" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeOtherDiemMonth2" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeOtherDiemMonth3" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeOtherFlightAverage" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeOtherFlightMonth1" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeOtherFlightMonth2" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeOtherFlightMonth3" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeOtherIncome" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeOtherOTAverage" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeOtherOTMonth1" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeOtherOTMonth2" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeOtherOTMonth3" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeSharedHolderPercent" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incomeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="incometotalLastMthCreditAcct1" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incometotalLastMthCreditAcct2" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="insiderCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="issuedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="lifeTimeFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mailingPreference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="maritalStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mobileNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nameLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nameLine2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nationality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nationality2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ncbConsentFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="noOfDependent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="originatedUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="personalInfoSavedFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="preScoreCash" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="professionalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="race" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="registerExtTelephoneNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="registerTelephoneNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="relationWithMain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="residentFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="residentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rmOccupation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rmWealthFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="salutationCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sameRegisterAddressFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="selfEmployInTotalIncome" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="selfEmployIncomeExtraOther" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="selfEmployIncomeExtraRental" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="selfEmployIncomeExtraTotal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="selfEmployIncomeTotal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="sourceFromCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sourceOfRisk" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="spBirthDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="spIdNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="spIdType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="spSalutationCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="spThaiName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="spThaiSurName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="spTitleTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="telephoneNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="thaiName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="thaiSalutationCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="thaiSurName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="titleTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="workingAddrCopyFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InstantIndividual", propOrder = {
    "accounts",
    "addresses",
    "age",
    "ageMonth",
    "benefitPlusSegment",
    "birthDate",
    "birthPlace",
    "bonusYearly",
    "businessSubType",
    "businessType",
    "caId",
    "cifId",
    "cifRelCode",
    "companyType",
    "contractEmpEndDate",
    "contractEmpStartDate",
    "contractEmployedFlag",
    "countryOfRegAddr",
    "creditCards",
    "currentEmployerCode",
    "currentJobTitle",
    "custContactTime",
    "customerLevel",
    "customerRiskRM",
    "customerType",
    "discloseCustInfoFlag",
    "educationLevel",
    "email",
    "emailStatementFlag",
    "employmentBizNature",
    "employmentDept",
    "employmentFaxNo",
    "employmentFinalTotalIncome",
    "employmentInfoSavedFlag",
    "employmentMonth",
    "employmentName",
    "employmentOccupation",
    "employmentProvince",
    "employmentStaffId",
    "employmentStatus",
    "employmentTelephoneDirectNo",
    "employmentTelephoneExtNo",
    "employmentTelephoneNo",
    "employmentYear",
    "excludeIncomeDebtFlag",
    "existingSavingTDAccount",
    "expiryDate",
    "extTelephoneNo",
    "fixNetAsset",
    "gender",
    "hostCifNo",
    "idIssueCtry1",
    "idNo1",
    "idType1",
    "idenPresentToBank",
    "inTotalExtraIncome",
    "inTotalFixedIncome",
    "inTotalIncome",
    "inTotalOtherIncome",
    "includeIncomeFlag",
    "incomeBankAccoutNumber",
    "incomeBankName",
    "incomeBasicSalary",
    "incomeDeclared",
    "incomeExtraOther",
    "incomeExtraRental",
    "incomeInfoSavedFlag",
    "incomeOtherCommAverage",
    "incomeOtherCommMonth1",
    "incomeOtherCommMonth2",
    "incomeOtherCommMonth3",
    "incomeOtherDiemAverage",
    "incomeOtherDiemMonth1",
    "incomeOtherDiemMonth2",
    "incomeOtherDiemMonth3",
    "incomeOtherFlightAverage",
    "incomeOtherFlightMonth1",
    "incomeOtherFlightMonth2",
    "incomeOtherFlightMonth3",
    "incomeOtherIncome",
    "incomeOtherOTAverage",
    "incomeOtherOTMonth1",
    "incomeOtherOTMonth2",
    "incomeOtherOTMonth3",
    "incomeSharedHolderPercent",
    "incomeType",
    "incometotalLastMthCreditAcct1",
    "incometotalLastMthCreditAcct2",
    "insiderCode",
    "issuedDate",
    "lifeTimeFlag",
    "mailingPreference",
    "maritalStatus",
    "mobileNo",
    "nameLine1",
    "nameLine2",
    "nationality",
    "nationality2",
    "ncbConsentFlag",
    "noOfDependent",
    "originatedUnit",
    "personalInfoSavedFlag",
    "preScoreCash",
    "professionalCode",
    "race",
    "registerExtTelephoneNo",
    "registerTelephoneNo",
    "relationWithMain",
    "residentFlag",
    "residentType",
    "rmOccupation",
    "rmWealthFlag",
    "salutationCode",
    "sameRegisterAddressFlag",
    "selfEmployInTotalIncome",
    "selfEmployIncomeExtraOther",
    "selfEmployIncomeExtraRental",
    "selfEmployIncomeExtraTotal",
    "selfEmployIncomeTotal",
    "sourceFromCountry",
    "sourceOfRisk",
    "spBirthDate",
    "spIdNo",
    "spIdType",
    "spSalutationCode",
    "spThaiName",
    "spThaiSurName",
    "spTitleTypeCode",
    "telephoneNo",
    "thaiName",
    "thaiSalutationCode",
    "thaiSurName",
    "titleTypeCode",
    "workingAddrCopyFrom"
})
public class InstantIndividual {

    @XmlElement(required = true, nillable = true)
    protected ArrayOfTns5Account accounts;
    @XmlElement(required = true, nillable = true)
    protected ArrayOfTns6Address addresses;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal age;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal ageMonth;
    @XmlElement(required = true, nillable = true)
    protected String benefitPlusSegment;
    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar birthDate;
    @XmlElement(required = true, nillable = true)
    protected String birthPlace;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal bonusYearly;
    @XmlElement(required = true, nillable = true)
    protected String businessSubType;
    @XmlElement(required = true, nillable = true)
    protected String businessType;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal caId;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal cifId;
    @XmlElement(required = true, nillable = true)
    protected String cifRelCode;
    @XmlElement(required = true, nillable = true)
    protected String companyType;
    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar contractEmpEndDate;
    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar contractEmpStartDate;
    @XmlElement(required = true, nillable = true)
    protected String contractEmployedFlag;
    @XmlElement(required = true, nillable = true)
    protected String countryOfRegAddr;
    @XmlElement(required = true, nillable = true)
    protected ArrayOfTns7InstantCreditCard creditCards;
    @XmlElement(required = true, nillable = true)
    protected String currentEmployerCode;
    @XmlElement(required = true, nillable = true)
    protected String currentJobTitle;
    @XmlElement(required = true, nillable = true)
    protected String custContactTime;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal customerLevel;
    @XmlElement(required = true, nillable = true)
    protected String customerRiskRM;
    @XmlElement(required = true, nillable = true)
    protected String customerType;
    @XmlElement(required = true, nillable = true)
    protected String discloseCustInfoFlag;
    @XmlElement(required = true, nillable = true)
    protected String educationLevel;
    @XmlElement(required = true, nillable = true)
    protected String email;
    @XmlElement(required = true, nillable = true)
    protected String emailStatementFlag;
    @XmlElement(required = true, nillable = true)
    protected String employmentBizNature;
    @XmlElement(required = true, nillable = true)
    protected String employmentDept;
    @XmlElement(required = true, nillable = true)
    protected String employmentFaxNo;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal employmentFinalTotalIncome;
    @XmlElement(required = true, nillable = true)
    protected String employmentInfoSavedFlag;
    @XmlElement(required = true, nillable = true)
    protected String employmentMonth;
    @XmlElement(required = true, nillable = true)
    protected String employmentName;
    @XmlElement(required = true, nillable = true)
    protected String employmentOccupation;
    @XmlElement(required = true, nillable = true)
    protected String employmentProvince;
    @XmlElement(required = true, nillable = true)
    protected String employmentStaffId;
    @XmlElement(required = true, nillable = true)
    protected String employmentStatus;
    @XmlElement(required = true, nillable = true)
    protected String employmentTelephoneDirectNo;
    @XmlElement(required = true, nillable = true)
    protected String employmentTelephoneExtNo;
    @XmlElement(required = true, nillable = true)
    protected String employmentTelephoneNo;
    @XmlElement(required = true, nillable = true)
    protected String employmentYear;
    @XmlElement(required = true, nillable = true)
    protected String excludeIncomeDebtFlag;
    @XmlElement(required = true, nillable = true)
    protected String existingSavingTDAccount;
    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expiryDate;
    @XmlElement(required = true, nillable = true)
    protected String extTelephoneNo;
    @XmlElement(required = true, nillable = true)
    protected String fixNetAsset;
    @XmlElement(required = true, nillable = true)
    protected String gender;
    @XmlElement(required = true, nillable = true)
    protected String hostCifNo;
    @XmlElement(required = true, nillable = true)
    protected String idIssueCtry1;
    @XmlElement(required = true, nillable = true)
    protected String idNo1;
    @XmlElement(required = true, nillable = true)
    protected String idType1;
    @XmlElement(required = true, nillable = true)
    protected String idenPresentToBank;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal inTotalExtraIncome;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal inTotalFixedIncome;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal inTotalIncome;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal inTotalOtherIncome;
    @XmlElement(required = true, nillable = true)
    protected String includeIncomeFlag;
    @XmlElement(required = true, nillable = true)
    protected String incomeBankAccoutNumber;
    @XmlElement(required = true, nillable = true)
    protected String incomeBankName;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeBasicSalary;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeDeclared;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeExtraOther;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeExtraRental;
    @XmlElement(required = true, nillable = true)
    protected String incomeInfoSavedFlag;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeOtherCommAverage;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeOtherCommMonth1;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeOtherCommMonth2;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeOtherCommMonth3;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeOtherDiemAverage;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeOtherDiemMonth1;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeOtherDiemMonth2;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeOtherDiemMonth3;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeOtherFlightAverage;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeOtherFlightMonth1;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeOtherFlightMonth2;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeOtherFlightMonth3;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeOtherIncome;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeOtherOTAverage;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeOtherOTMonth1;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeOtherOTMonth2;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeOtherOTMonth3;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incomeSharedHolderPercent;
    @XmlElement(required = true, nillable = true)
    protected String incomeType;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incometotalLastMthCreditAcct1;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal incometotalLastMthCreditAcct2;
    @XmlElement(required = true, nillable = true)
    protected String insiderCode;
    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar issuedDate;
    @XmlElement(required = true, nillable = true)
    protected String lifeTimeFlag;
    @XmlElement(required = true, nillable = true)
    protected String mailingPreference;
    @XmlElement(required = true, nillable = true)
    protected String maritalStatus;
    @XmlElement(required = true, nillable = true)
    protected String mobileNo;
    @XmlElement(required = true, nillable = true)
    protected String nameLine1;
    @XmlElement(required = true, nillable = true)
    protected String nameLine2;
    @XmlElement(required = true, nillable = true)
    protected String nationality;
    @XmlElement(required = true, nillable = true)
    protected String nationality2;
    @XmlElement(required = true, nillable = true)
    protected String ncbConsentFlag;
    @XmlElement(required = true, nillable = true)
    protected String noOfDependent;
    @XmlElement(required = true, nillable = true)
    protected String originatedUnit;
    @XmlElement(required = true, nillable = true)
    protected String personalInfoSavedFlag;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal preScoreCash;
    @XmlElement(required = true, nillable = true)
    protected String professionalCode;
    @XmlElement(required = true, nillable = true)
    protected String race;
    @XmlElement(required = true, nillable = true)
    protected String registerExtTelephoneNo;
    @XmlElement(required = true, nillable = true)
    protected String registerTelephoneNo;
    @XmlElement(required = true, nillable = true)
    protected String relationWithMain;
    @XmlElement(required = true, nillable = true)
    protected String residentFlag;
    @XmlElement(required = true, nillable = true)
    protected String residentType;
    @XmlElement(required = true, nillable = true)
    protected String rmOccupation;
    @XmlElement(required = true, nillable = true)
    protected String rmWealthFlag;
    @XmlElement(required = true, nillable = true)
    protected String salutationCode;
    @XmlElement(required = true, nillable = true)
    protected String sameRegisterAddressFlag;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal selfEmployInTotalIncome;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal selfEmployIncomeExtraOther;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal selfEmployIncomeExtraRental;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal selfEmployIncomeExtraTotal;
    @XmlElement(required = true, nillable = true)
    protected BigDecimal selfEmployIncomeTotal;
    @XmlElement(required = true, nillable = true)
    protected String sourceFromCountry;
    @XmlElement(required = true, nillable = true)
    protected String sourceOfRisk;
    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar spBirthDate;
    @XmlElement(required = true, nillable = true)
    protected String spIdNo;
    @XmlElement(required = true, nillable = true)
    protected String spIdType;
    @XmlElement(required = true, nillable = true)
    protected String spSalutationCode;
    @XmlElement(required = true, nillable = true)
    protected String spThaiName;
    @XmlElement(required = true, nillable = true)
    protected String spThaiSurName;
    @XmlElement(required = true, nillable = true)
    protected String spTitleTypeCode;
    @XmlElement(required = true, nillable = true)
    protected String telephoneNo;
    @XmlElement(required = true, nillable = true)
    protected String thaiName;
    @XmlElement(required = true, nillable = true)
    protected String thaiSalutationCode;
    @XmlElement(required = true, nillable = true)
    protected String thaiSurName;
    @XmlElement(required = true, nillable = true)
    protected String titleTypeCode;
    @XmlElement(required = true, nillable = true)
    protected String workingAddrCopyFrom;

    /**
     * Gets the value of the accounts property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTns5Account }
     *     
     */
    public ArrayOfTns5Account getAccounts() {
        return accounts;
    }

    /**
     * Sets the value of the accounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTns5Account }
     *     
     */
    public void setAccounts(ArrayOfTns5Account value) {
        this.accounts = value;
    }

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTns6Address }
     *     
     */
    public ArrayOfTns6Address getAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTns6Address }
     *     
     */
    public void setAddresses(ArrayOfTns6Address value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAge(BigDecimal value) {
        this.age = value;
    }

    /**
     * Gets the value of the ageMonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAgeMonth() {
        return ageMonth;
    }

    /**
     * Sets the value of the ageMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAgeMonth(BigDecimal value) {
        this.ageMonth = value;
    }

    /**
     * Gets the value of the benefitPlusSegment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenefitPlusSegment() {
        return benefitPlusSegment;
    }

    /**
     * Sets the value of the benefitPlusSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenefitPlusSegment(String value) {
        this.benefitPlusSegment = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDate(XMLGregorianCalendar value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the birthPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthPlace() {
        return birthPlace;
    }

    /**
     * Sets the value of the birthPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthPlace(String value) {
        this.birthPlace = value;
    }

    /**
     * Gets the value of the bonusYearly property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBonusYearly() {
        return bonusYearly;
    }

    /**
     * Sets the value of the bonusYearly property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBonusYearly(BigDecimal value) {
        this.bonusYearly = value;
    }

    /**
     * Gets the value of the businessSubType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessSubType() {
        return businessSubType;
    }

    /**
     * Sets the value of the businessSubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessSubType(String value) {
        this.businessSubType = value;
    }

    /**
     * Gets the value of the businessType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * Sets the value of the businessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessType(String value) {
        this.businessType = value;
    }

    /**
     * Gets the value of the caId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCaId() {
        return caId;
    }

    /**
     * Sets the value of the caId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCaId(BigDecimal value) {
        this.caId = value;
    }

    /**
     * Gets the value of the cifId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCifId() {
        return cifId;
    }

    /**
     * Sets the value of the cifId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCifId(BigDecimal value) {
        this.cifId = value;
    }

    /**
     * Gets the value of the cifRelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCifRelCode() {
        return cifRelCode;
    }

    /**
     * Sets the value of the cifRelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCifRelCode(String value) {
        this.cifRelCode = value;
    }

    /**
     * Gets the value of the companyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyType() {
        return companyType;
    }

    /**
     * Sets the value of the companyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyType(String value) {
        this.companyType = value;
    }

    /**
     * Gets the value of the contractEmpEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContractEmpEndDate() {
        return contractEmpEndDate;
    }

    /**
     * Sets the value of the contractEmpEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContractEmpEndDate(XMLGregorianCalendar value) {
        this.contractEmpEndDate = value;
    }

    /**
     * Gets the value of the contractEmpStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContractEmpStartDate() {
        return contractEmpStartDate;
    }

    /**
     * Sets the value of the contractEmpStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContractEmpStartDate(XMLGregorianCalendar value) {
        this.contractEmpStartDate = value;
    }

    /**
     * Gets the value of the contractEmployedFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractEmployedFlag() {
        return contractEmployedFlag;
    }

    /**
     * Sets the value of the contractEmployedFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractEmployedFlag(String value) {
        this.contractEmployedFlag = value;
    }

    /**
     * Gets the value of the countryOfRegAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfRegAddr() {
        return countryOfRegAddr;
    }

    /**
     * Sets the value of the countryOfRegAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfRegAddr(String value) {
        this.countryOfRegAddr = value;
    }

    /**
     * Gets the value of the creditCards property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTns7InstantCreditCard }
     *     
     */
    public ArrayOfTns7InstantCreditCard getCreditCards() {
        return creditCards;
    }

    /**
     * Sets the value of the creditCards property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTns7InstantCreditCard }
     *     
     */
    public void setCreditCards(ArrayOfTns7InstantCreditCard value) {
        this.creditCards = value;
    }

    /**
     * Gets the value of the currentEmployerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentEmployerCode() {
        return currentEmployerCode;
    }

    /**
     * Sets the value of the currentEmployerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentEmployerCode(String value) {
        this.currentEmployerCode = value;
    }

    /**
     * Gets the value of the currentJobTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentJobTitle() {
        return currentJobTitle;
    }

    /**
     * Sets the value of the currentJobTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentJobTitle(String value) {
        this.currentJobTitle = value;
    }

    /**
     * Gets the value of the custContactTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustContactTime() {
        return custContactTime;
    }

    /**
     * Sets the value of the custContactTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustContactTime(String value) {
        this.custContactTime = value;
    }

    /**
     * Gets the value of the customerLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCustomerLevel() {
        return customerLevel;
    }

    /**
     * Sets the value of the customerLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCustomerLevel(BigDecimal value) {
        this.customerLevel = value;
    }

    /**
     * Gets the value of the customerRiskRM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerRiskRM() {
        return customerRiskRM;
    }

    /**
     * Sets the value of the customerRiskRM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerRiskRM(String value) {
        this.customerRiskRM = value;
    }

    /**
     * Gets the value of the customerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * Sets the value of the customerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerType(String value) {
        this.customerType = value;
    }

    /**
     * Gets the value of the discloseCustInfoFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscloseCustInfoFlag() {
        return discloseCustInfoFlag;
    }

    /**
     * Sets the value of the discloseCustInfoFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscloseCustInfoFlag(String value) {
        this.discloseCustInfoFlag = value;
    }

    /**
     * Gets the value of the educationLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEducationLevel() {
        return educationLevel;
    }

    /**
     * Sets the value of the educationLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEducationLevel(String value) {
        this.educationLevel = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the emailStatementFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailStatementFlag() {
        return emailStatementFlag;
    }

    /**
     * Sets the value of the emailStatementFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailStatementFlag(String value) {
        this.emailStatementFlag = value;
    }

    /**
     * Gets the value of the employmentBizNature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentBizNature() {
        return employmentBizNature;
    }

    /**
     * Sets the value of the employmentBizNature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentBizNature(String value) {
        this.employmentBizNature = value;
    }

    /**
     * Gets the value of the employmentDept property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentDept() {
        return employmentDept;
    }

    /**
     * Sets the value of the employmentDept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentDept(String value) {
        this.employmentDept = value;
    }

    /**
     * Gets the value of the employmentFaxNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentFaxNo() {
        return employmentFaxNo;
    }

    /**
     * Sets the value of the employmentFaxNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentFaxNo(String value) {
        this.employmentFaxNo = value;
    }

    /**
     * Gets the value of the employmentFinalTotalIncome property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEmploymentFinalTotalIncome() {
        return employmentFinalTotalIncome;
    }

    /**
     * Sets the value of the employmentFinalTotalIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEmploymentFinalTotalIncome(BigDecimal value) {
        this.employmentFinalTotalIncome = value;
    }

    /**
     * Gets the value of the employmentInfoSavedFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentInfoSavedFlag() {
        return employmentInfoSavedFlag;
    }

    /**
     * Sets the value of the employmentInfoSavedFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentInfoSavedFlag(String value) {
        this.employmentInfoSavedFlag = value;
    }

    /**
     * Gets the value of the employmentMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentMonth() {
        return employmentMonth;
    }

    /**
     * Sets the value of the employmentMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentMonth(String value) {
        this.employmentMonth = value;
    }

    /**
     * Gets the value of the employmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentName() {
        return employmentName;
    }

    /**
     * Sets the value of the employmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentName(String value) {
        this.employmentName = value;
    }

    /**
     * Gets the value of the employmentOccupation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentOccupation() {
        return employmentOccupation;
    }

    /**
     * Sets the value of the employmentOccupation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentOccupation(String value) {
        this.employmentOccupation = value;
    }

    /**
     * Gets the value of the employmentProvince property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentProvince() {
        return employmentProvince;
    }

    /**
     * Sets the value of the employmentProvince property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentProvince(String value) {
        this.employmentProvince = value;
    }

    /**
     * Gets the value of the employmentStaffId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentStaffId() {
        return employmentStaffId;
    }

    /**
     * Sets the value of the employmentStaffId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentStaffId(String value) {
        this.employmentStaffId = value;
    }

    /**
     * Gets the value of the employmentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentStatus() {
        return employmentStatus;
    }

    /**
     * Sets the value of the employmentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentStatus(String value) {
        this.employmentStatus = value;
    }

    /**
     * Gets the value of the employmentTelephoneDirectNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentTelephoneDirectNo() {
        return employmentTelephoneDirectNo;
    }

    /**
     * Sets the value of the employmentTelephoneDirectNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentTelephoneDirectNo(String value) {
        this.employmentTelephoneDirectNo = value;
    }

    /**
     * Gets the value of the employmentTelephoneExtNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentTelephoneExtNo() {
        return employmentTelephoneExtNo;
    }

    /**
     * Sets the value of the employmentTelephoneExtNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentTelephoneExtNo(String value) {
        this.employmentTelephoneExtNo = value;
    }

    /**
     * Gets the value of the employmentTelephoneNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentTelephoneNo() {
        return employmentTelephoneNo;
    }

    /**
     * Sets the value of the employmentTelephoneNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentTelephoneNo(String value) {
        this.employmentTelephoneNo = value;
    }

    /**
     * Gets the value of the employmentYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentYear() {
        return employmentYear;
    }

    /**
     * Sets the value of the employmentYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentYear(String value) {
        this.employmentYear = value;
    }

    /**
     * Gets the value of the excludeIncomeDebtFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcludeIncomeDebtFlag() {
        return excludeIncomeDebtFlag;
    }

    /**
     * Sets the value of the excludeIncomeDebtFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcludeIncomeDebtFlag(String value) {
        this.excludeIncomeDebtFlag = value;
    }

    /**
     * Gets the value of the existingSavingTDAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExistingSavingTDAccount() {
        return existingSavingTDAccount;
    }

    /**
     * Sets the value of the existingSavingTDAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExistingSavingTDAccount(String value) {
        this.existingSavingTDAccount = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpiryDate(XMLGregorianCalendar value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the extTelephoneNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtTelephoneNo() {
        return extTelephoneNo;
    }

    /**
     * Sets the value of the extTelephoneNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtTelephoneNo(String value) {
        this.extTelephoneNo = value;
    }

    /**
     * Gets the value of the fixNetAsset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixNetAsset() {
        return fixNetAsset;
    }

    /**
     * Sets the value of the fixNetAsset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixNetAsset(String value) {
        this.fixNetAsset = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the hostCifNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostCifNo() {
        return hostCifNo;
    }

    /**
     * Sets the value of the hostCifNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostCifNo(String value) {
        this.hostCifNo = value;
    }

    /**
     * Gets the value of the idIssueCtry1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdIssueCtry1() {
        return idIssueCtry1;
    }

    /**
     * Sets the value of the idIssueCtry1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdIssueCtry1(String value) {
        this.idIssueCtry1 = value;
    }

    /**
     * Gets the value of the idNo1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdNo1() {
        return idNo1;
    }

    /**
     * Sets the value of the idNo1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdNo1(String value) {
        this.idNo1 = value;
    }

    /**
     * Gets the value of the idType1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdType1() {
        return idType1;
    }

    /**
     * Sets the value of the idType1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdType1(String value) {
        this.idType1 = value;
    }

    /**
     * Gets the value of the idenPresentToBank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdenPresentToBank() {
        return idenPresentToBank;
    }

    /**
     * Sets the value of the idenPresentToBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdenPresentToBank(String value) {
        this.idenPresentToBank = value;
    }

    /**
     * Gets the value of the inTotalExtraIncome property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInTotalExtraIncome() {
        return inTotalExtraIncome;
    }

    /**
     * Sets the value of the inTotalExtraIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInTotalExtraIncome(BigDecimal value) {
        this.inTotalExtraIncome = value;
    }

    /**
     * Gets the value of the inTotalFixedIncome property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInTotalFixedIncome() {
        return inTotalFixedIncome;
    }

    /**
     * Sets the value of the inTotalFixedIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInTotalFixedIncome(BigDecimal value) {
        this.inTotalFixedIncome = value;
    }

    /**
     * Gets the value of the inTotalIncome property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInTotalIncome() {
        return inTotalIncome;
    }

    /**
     * Sets the value of the inTotalIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInTotalIncome(BigDecimal value) {
        this.inTotalIncome = value;
    }

    /**
     * Gets the value of the inTotalOtherIncome property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInTotalOtherIncome() {
        return inTotalOtherIncome;
    }

    /**
     * Sets the value of the inTotalOtherIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInTotalOtherIncome(BigDecimal value) {
        this.inTotalOtherIncome = value;
    }

    /**
     * Gets the value of the includeIncomeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncludeIncomeFlag() {
        return includeIncomeFlag;
    }

    /**
     * Sets the value of the includeIncomeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncludeIncomeFlag(String value) {
        this.includeIncomeFlag = value;
    }

    /**
     * Gets the value of the incomeBankAccoutNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncomeBankAccoutNumber() {
        return incomeBankAccoutNumber;
    }

    /**
     * Sets the value of the incomeBankAccoutNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncomeBankAccoutNumber(String value) {
        this.incomeBankAccoutNumber = value;
    }

    /**
     * Gets the value of the incomeBankName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncomeBankName() {
        return incomeBankName;
    }

    /**
     * Sets the value of the incomeBankName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncomeBankName(String value) {
        this.incomeBankName = value;
    }

    /**
     * Gets the value of the incomeBasicSalary property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeBasicSalary() {
        return incomeBasicSalary;
    }

    /**
     * Sets the value of the incomeBasicSalary property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeBasicSalary(BigDecimal value) {
        this.incomeBasicSalary = value;
    }

    /**
     * Gets the value of the incomeDeclared property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeDeclared() {
        return incomeDeclared;
    }

    /**
     * Sets the value of the incomeDeclared property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeDeclared(BigDecimal value) {
        this.incomeDeclared = value;
    }

    /**
     * Gets the value of the incomeExtraOther property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeExtraOther() {
        return incomeExtraOther;
    }

    /**
     * Sets the value of the incomeExtraOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeExtraOther(BigDecimal value) {
        this.incomeExtraOther = value;
    }

    /**
     * Gets the value of the incomeExtraRental property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeExtraRental() {
        return incomeExtraRental;
    }

    /**
     * Sets the value of the incomeExtraRental property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeExtraRental(BigDecimal value) {
        this.incomeExtraRental = value;
    }

    /**
     * Gets the value of the incomeInfoSavedFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncomeInfoSavedFlag() {
        return incomeInfoSavedFlag;
    }

    /**
     * Sets the value of the incomeInfoSavedFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncomeInfoSavedFlag(String value) {
        this.incomeInfoSavedFlag = value;
    }

    /**
     * Gets the value of the incomeOtherCommAverage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeOtherCommAverage() {
        return incomeOtherCommAverage;
    }

    /**
     * Sets the value of the incomeOtherCommAverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeOtherCommAverage(BigDecimal value) {
        this.incomeOtherCommAverage = value;
    }

    /**
     * Gets the value of the incomeOtherCommMonth1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeOtherCommMonth1() {
        return incomeOtherCommMonth1;
    }

    /**
     * Sets the value of the incomeOtherCommMonth1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeOtherCommMonth1(BigDecimal value) {
        this.incomeOtherCommMonth1 = value;
    }

    /**
     * Gets the value of the incomeOtherCommMonth2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeOtherCommMonth2() {
        return incomeOtherCommMonth2;
    }

    /**
     * Sets the value of the incomeOtherCommMonth2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeOtherCommMonth2(BigDecimal value) {
        this.incomeOtherCommMonth2 = value;
    }

    /**
     * Gets the value of the incomeOtherCommMonth3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeOtherCommMonth3() {
        return incomeOtherCommMonth3;
    }

    /**
     * Sets the value of the incomeOtherCommMonth3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeOtherCommMonth3(BigDecimal value) {
        this.incomeOtherCommMonth3 = value;
    }

    /**
     * Gets the value of the incomeOtherDiemAverage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeOtherDiemAverage() {
        return incomeOtherDiemAverage;
    }

    /**
     * Sets the value of the incomeOtherDiemAverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeOtherDiemAverage(BigDecimal value) {
        this.incomeOtherDiemAverage = value;
    }

    /**
     * Gets the value of the incomeOtherDiemMonth1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeOtherDiemMonth1() {
        return incomeOtherDiemMonth1;
    }

    /**
     * Sets the value of the incomeOtherDiemMonth1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeOtherDiemMonth1(BigDecimal value) {
        this.incomeOtherDiemMonth1 = value;
    }

    /**
     * Gets the value of the incomeOtherDiemMonth2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeOtherDiemMonth2() {
        return incomeOtherDiemMonth2;
    }

    /**
     * Sets the value of the incomeOtherDiemMonth2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeOtherDiemMonth2(BigDecimal value) {
        this.incomeOtherDiemMonth2 = value;
    }

    /**
     * Gets the value of the incomeOtherDiemMonth3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeOtherDiemMonth3() {
        return incomeOtherDiemMonth3;
    }

    /**
     * Sets the value of the incomeOtherDiemMonth3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeOtherDiemMonth3(BigDecimal value) {
        this.incomeOtherDiemMonth3 = value;
    }

    /**
     * Gets the value of the incomeOtherFlightAverage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeOtherFlightAverage() {
        return incomeOtherFlightAverage;
    }

    /**
     * Sets the value of the incomeOtherFlightAverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeOtherFlightAverage(BigDecimal value) {
        this.incomeOtherFlightAverage = value;
    }

    /**
     * Gets the value of the incomeOtherFlightMonth1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeOtherFlightMonth1() {
        return incomeOtherFlightMonth1;
    }

    /**
     * Sets the value of the incomeOtherFlightMonth1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeOtherFlightMonth1(BigDecimal value) {
        this.incomeOtherFlightMonth1 = value;
    }

    /**
     * Gets the value of the incomeOtherFlightMonth2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeOtherFlightMonth2() {
        return incomeOtherFlightMonth2;
    }

    /**
     * Sets the value of the incomeOtherFlightMonth2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeOtherFlightMonth2(BigDecimal value) {
        this.incomeOtherFlightMonth2 = value;
    }

    /**
     * Gets the value of the incomeOtherFlightMonth3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeOtherFlightMonth3() {
        return incomeOtherFlightMonth3;
    }

    /**
     * Sets the value of the incomeOtherFlightMonth3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeOtherFlightMonth3(BigDecimal value) {
        this.incomeOtherFlightMonth3 = value;
    }

    /**
     * Gets the value of the incomeOtherIncome property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeOtherIncome() {
        return incomeOtherIncome;
    }

    /**
     * Sets the value of the incomeOtherIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeOtherIncome(BigDecimal value) {
        this.incomeOtherIncome = value;
    }

    /**
     * Gets the value of the incomeOtherOTAverage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeOtherOTAverage() {
        return incomeOtherOTAverage;
    }

    /**
     * Sets the value of the incomeOtherOTAverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeOtherOTAverage(BigDecimal value) {
        this.incomeOtherOTAverage = value;
    }

    /**
     * Gets the value of the incomeOtherOTMonth1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeOtherOTMonth1() {
        return incomeOtherOTMonth1;
    }

    /**
     * Sets the value of the incomeOtherOTMonth1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeOtherOTMonth1(BigDecimal value) {
        this.incomeOtherOTMonth1 = value;
    }

    /**
     * Gets the value of the incomeOtherOTMonth2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeOtherOTMonth2() {
        return incomeOtherOTMonth2;
    }

    /**
     * Sets the value of the incomeOtherOTMonth2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeOtherOTMonth2(BigDecimal value) {
        this.incomeOtherOTMonth2 = value;
    }

    /**
     * Gets the value of the incomeOtherOTMonth3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeOtherOTMonth3() {
        return incomeOtherOTMonth3;
    }

    /**
     * Sets the value of the incomeOtherOTMonth3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeOtherOTMonth3(BigDecimal value) {
        this.incomeOtherOTMonth3 = value;
    }

    /**
     * Gets the value of the incomeSharedHolderPercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncomeSharedHolderPercent() {
        return incomeSharedHolderPercent;
    }

    /**
     * Sets the value of the incomeSharedHolderPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncomeSharedHolderPercent(BigDecimal value) {
        this.incomeSharedHolderPercent = value;
    }

    /**
     * Gets the value of the incomeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncomeType() {
        return incomeType;
    }

    /**
     * Sets the value of the incomeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncomeType(String value) {
        this.incomeType = value;
    }

    /**
     * Gets the value of the incometotalLastMthCreditAcct1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncometotalLastMthCreditAcct1() {
        return incometotalLastMthCreditAcct1;
    }

    /**
     * Sets the value of the incometotalLastMthCreditAcct1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncometotalLastMthCreditAcct1(BigDecimal value) {
        this.incometotalLastMthCreditAcct1 = value;
    }

    /**
     * Gets the value of the incometotalLastMthCreditAcct2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncometotalLastMthCreditAcct2() {
        return incometotalLastMthCreditAcct2;
    }

    /**
     * Sets the value of the incometotalLastMthCreditAcct2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncometotalLastMthCreditAcct2(BigDecimal value) {
        this.incometotalLastMthCreditAcct2 = value;
    }

    /**
     * Gets the value of the insiderCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsiderCode() {
        return insiderCode;
    }

    /**
     * Sets the value of the insiderCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsiderCode(String value) {
        this.insiderCode = value;
    }

    /**
     * Gets the value of the issuedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIssuedDate() {
        return issuedDate;
    }

    /**
     * Sets the value of the issuedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIssuedDate(XMLGregorianCalendar value) {
        this.issuedDate = value;
    }

    /**
     * Gets the value of the lifeTimeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLifeTimeFlag() {
        return lifeTimeFlag;
    }

    /**
     * Sets the value of the lifeTimeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLifeTimeFlag(String value) {
        this.lifeTimeFlag = value;
    }

    /**
     * Gets the value of the mailingPreference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailingPreference() {
        return mailingPreference;
    }

    /**
     * Sets the value of the mailingPreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailingPreference(String value) {
        this.mailingPreference = value;
    }

    /**
     * Gets the value of the maritalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * Sets the value of the maritalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaritalStatus(String value) {
        this.maritalStatus = value;
    }

    /**
     * Gets the value of the mobileNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * Sets the value of the mobileNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileNo(String value) {
        this.mobileNo = value;
    }

    /**
     * Gets the value of the nameLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameLine1() {
        return nameLine1;
    }

    /**
     * Sets the value of the nameLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameLine1(String value) {
        this.nameLine1 = value;
    }

    /**
     * Gets the value of the nameLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameLine2() {
        return nameLine2;
    }

    /**
     * Sets the value of the nameLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameLine2(String value) {
        this.nameLine2 = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationality(String value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the nationality2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationality2() {
        return nationality2;
    }

    /**
     * Sets the value of the nationality2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationality2(String value) {
        this.nationality2 = value;
    }

    /**
     * Gets the value of the ncbConsentFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNcbConsentFlag() {
        return ncbConsentFlag;
    }

    /**
     * Sets the value of the ncbConsentFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNcbConsentFlag(String value) {
        this.ncbConsentFlag = value;
    }

    /**
     * Gets the value of the noOfDependent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoOfDependent() {
        return noOfDependent;
    }

    /**
     * Sets the value of the noOfDependent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoOfDependent(String value) {
        this.noOfDependent = value;
    }

    /**
     * Gets the value of the originatedUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatedUnit() {
        return originatedUnit;
    }

    /**
     * Sets the value of the originatedUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatedUnit(String value) {
        this.originatedUnit = value;
    }

    /**
     * Gets the value of the personalInfoSavedFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalInfoSavedFlag() {
        return personalInfoSavedFlag;
    }

    /**
     * Sets the value of the personalInfoSavedFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalInfoSavedFlag(String value) {
        this.personalInfoSavedFlag = value;
    }

    /**
     * Gets the value of the preScoreCash property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPreScoreCash() {
        return preScoreCash;
    }

    /**
     * Sets the value of the preScoreCash property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPreScoreCash(BigDecimal value) {
        this.preScoreCash = value;
    }

    /**
     * Gets the value of the professionalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfessionalCode() {
        return professionalCode;
    }

    /**
     * Sets the value of the professionalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfessionalCode(String value) {
        this.professionalCode = value;
    }

    /**
     * Gets the value of the race property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRace() {
        return race;
    }

    /**
     * Sets the value of the race property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRace(String value) {
        this.race = value;
    }

    /**
     * Gets the value of the registerExtTelephoneNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegisterExtTelephoneNo() {
        return registerExtTelephoneNo;
    }

    /**
     * Sets the value of the registerExtTelephoneNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegisterExtTelephoneNo(String value) {
        this.registerExtTelephoneNo = value;
    }

    /**
     * Gets the value of the registerTelephoneNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegisterTelephoneNo() {
        return registerTelephoneNo;
    }

    /**
     * Sets the value of the registerTelephoneNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegisterTelephoneNo(String value) {
        this.registerTelephoneNo = value;
    }

    /**
     * Gets the value of the relationWithMain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationWithMain() {
        return relationWithMain;
    }

    /**
     * Sets the value of the relationWithMain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationWithMain(String value) {
        this.relationWithMain = value;
    }

    /**
     * Gets the value of the residentFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResidentFlag() {
        return residentFlag;
    }

    /**
     * Sets the value of the residentFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResidentFlag(String value) {
        this.residentFlag = value;
    }

    /**
     * Gets the value of the residentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResidentType() {
        return residentType;
    }

    /**
     * Sets the value of the residentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResidentType(String value) {
        this.residentType = value;
    }

    /**
     * Gets the value of the rmOccupation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRmOccupation() {
        return rmOccupation;
    }

    /**
     * Sets the value of the rmOccupation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRmOccupation(String value) {
        this.rmOccupation = value;
    }

    /**
     * Gets the value of the rmWealthFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRmWealthFlag() {
        return rmWealthFlag;
    }

    /**
     * Sets the value of the rmWealthFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRmWealthFlag(String value) {
        this.rmWealthFlag = value;
    }

    /**
     * Gets the value of the salutationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalutationCode() {
        return salutationCode;
    }

    /**
     * Sets the value of the salutationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalutationCode(String value) {
        this.salutationCode = value;
    }

    /**
     * Gets the value of the sameRegisterAddressFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSameRegisterAddressFlag() {
        return sameRegisterAddressFlag;
    }

    /**
     * Sets the value of the sameRegisterAddressFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSameRegisterAddressFlag(String value) {
        this.sameRegisterAddressFlag = value;
    }

    /**
     * Gets the value of the selfEmployInTotalIncome property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSelfEmployInTotalIncome() {
        return selfEmployInTotalIncome;
    }

    /**
     * Sets the value of the selfEmployInTotalIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSelfEmployInTotalIncome(BigDecimal value) {
        this.selfEmployInTotalIncome = value;
    }

    /**
     * Gets the value of the selfEmployIncomeExtraOther property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSelfEmployIncomeExtraOther() {
        return selfEmployIncomeExtraOther;
    }

    /**
     * Sets the value of the selfEmployIncomeExtraOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSelfEmployIncomeExtraOther(BigDecimal value) {
        this.selfEmployIncomeExtraOther = value;
    }

    /**
     * Gets the value of the selfEmployIncomeExtraRental property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSelfEmployIncomeExtraRental() {
        return selfEmployIncomeExtraRental;
    }

    /**
     * Sets the value of the selfEmployIncomeExtraRental property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSelfEmployIncomeExtraRental(BigDecimal value) {
        this.selfEmployIncomeExtraRental = value;
    }

    /**
     * Gets the value of the selfEmployIncomeExtraTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSelfEmployIncomeExtraTotal() {
        return selfEmployIncomeExtraTotal;
    }

    /**
     * Sets the value of the selfEmployIncomeExtraTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSelfEmployIncomeExtraTotal(BigDecimal value) {
        this.selfEmployIncomeExtraTotal = value;
    }

    /**
     * Gets the value of the selfEmployIncomeTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSelfEmployIncomeTotal() {
        return selfEmployIncomeTotal;
    }

    /**
     * Sets the value of the selfEmployIncomeTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSelfEmployIncomeTotal(BigDecimal value) {
        this.selfEmployIncomeTotal = value;
    }

    /**
     * Gets the value of the sourceFromCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceFromCountry() {
        return sourceFromCountry;
    }

    /**
     * Sets the value of the sourceFromCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceFromCountry(String value) {
        this.sourceFromCountry = value;
    }

    /**
     * Gets the value of the sourceOfRisk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceOfRisk() {
        return sourceOfRisk;
    }

    /**
     * Sets the value of the sourceOfRisk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceOfRisk(String value) {
        this.sourceOfRisk = value;
    }

    /**
     * Gets the value of the spBirthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSpBirthDate() {
        return spBirthDate;
    }

    /**
     * Sets the value of the spBirthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSpBirthDate(XMLGregorianCalendar value) {
        this.spBirthDate = value;
    }

    /**
     * Gets the value of the spIdNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpIdNo() {
        return spIdNo;
    }

    /**
     * Sets the value of the spIdNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpIdNo(String value) {
        this.spIdNo = value;
    }

    /**
     * Gets the value of the spIdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpIdType() {
        return spIdType;
    }

    /**
     * Sets the value of the spIdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpIdType(String value) {
        this.spIdType = value;
    }

    /**
     * Gets the value of the spSalutationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpSalutationCode() {
        return spSalutationCode;
    }

    /**
     * Sets the value of the spSalutationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpSalutationCode(String value) {
        this.spSalutationCode = value;
    }

    /**
     * Gets the value of the spThaiName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpThaiName() {
        return spThaiName;
    }

    /**
     * Sets the value of the spThaiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpThaiName(String value) {
        this.spThaiName = value;
    }

    /**
     * Gets the value of the spThaiSurName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpThaiSurName() {
        return spThaiSurName;
    }

    /**
     * Sets the value of the spThaiSurName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpThaiSurName(String value) {
        this.spThaiSurName = value;
    }

    /**
     * Gets the value of the spTitleTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpTitleTypeCode() {
        return spTitleTypeCode;
    }

    /**
     * Sets the value of the spTitleTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpTitleTypeCode(String value) {
        this.spTitleTypeCode = value;
    }

    /**
     * Gets the value of the telephoneNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelephoneNo() {
        return telephoneNo;
    }

    /**
     * Sets the value of the telephoneNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelephoneNo(String value) {
        this.telephoneNo = value;
    }

    /**
     * Gets the value of the thaiName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThaiName() {
        return thaiName;
    }

    /**
     * Sets the value of the thaiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThaiName(String value) {
        this.thaiName = value;
    }

    /**
     * Gets the value of the thaiSalutationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThaiSalutationCode() {
        return thaiSalutationCode;
    }

    /**
     * Sets the value of the thaiSalutationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThaiSalutationCode(String value) {
        this.thaiSalutationCode = value;
    }

    /**
     * Gets the value of the thaiSurName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThaiSurName() {
        return thaiSurName;
    }

    /**
     * Sets the value of the thaiSurName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThaiSurName(String value) {
        this.thaiSurName = value;
    }

    /**
     * Gets the value of the titleTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleTypeCode() {
        return titleTypeCode;
    }

    /**
     * Sets the value of the titleTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleTypeCode(String value) {
        this.titleTypeCode = value;
    }

    /**
     * Gets the value of the workingAddrCopyFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkingAddrCopyFrom() {
        return workingAddrCopyFrom;
    }

    /**
     * Sets the value of the workingAddrCopyFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkingAddrCopyFrom(String value) {
        this.workingAddrCopyFrom = value;
    }

}
