//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.05 at 06:16:27 PM ICT 
//


package com.integrosys.sml.ws.instant.eligible.customer.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.integrosys.sml.ws.loan.submission.ArrayOfTns4InstantIndividual;


/**
 * <p>Java class for Body complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Body">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hostCifNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="instantIndividual" type="{http://submission.loan.ws.sml.integrosys.com}ArrayOf_tns4_InstantIndividual"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Body", propOrder = {
    "hostCifNo",
    "instantIndividual"
})
public class Body {

    @XmlElement(required = true, nillable = true)
    protected String hostCifNo;
    @XmlElement(required = true, nillable = true)
    protected ArrayOfTns4InstantIndividual instantIndividual;

    /**
     * Gets the value of the hostCifNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostCifNo() {
        return hostCifNo;
    }

    /**
     * Sets the value of the hostCifNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostCifNo(String value) {
        this.hostCifNo = value;
    }

    /**
     * Gets the value of the instantIndividual property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTns4InstantIndividual }
     *     
     */
    public ArrayOfTns4InstantIndividual getInstantIndividual() {
        return instantIndividual;
    }

    /**
     * Sets the value of the instantIndividual property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTns4InstantIndividual }
     *     
     */
    public void setInstantIndividual(ArrayOfTns4InstantIndividual value) {
        this.instantIndividual = value;
    }

}
